package Calculette;


/**
* Calculette/AdditionPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculette.idl
* Wednesday, April 13, 2022 6:39:29 PM CEST
*/

public class AdditionPOATie extends AdditionPOA
{

  // Constructors

  public AdditionPOATie ( Calculette.AdditionOperations delegate ) {
      this._impl = delegate;
  }
  public AdditionPOATie ( Calculette.AdditionOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public Calculette.AdditionOperations _delegate() {
      return this._impl;
  }
  public void _delegate (Calculette.AdditionOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int add (int a, int b)
  {
    return _impl.add(a, b);
  } // add

  private Calculette.AdditionOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class AdditionPOATie
