package Calculette;


/**
* Calculette/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculette.idl
* Wednesday, April 13, 2022 6:39:29 PM CEST
*/

public interface AdditionOperations 
{
  int add (int a, int b);
} // interface AdditionOperations
