package Calculette;

/**
* Calculette/AdditionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculette.idl
* Wednesday, April 13, 2022 6:39:29 PM CEST
*/

public final class AdditionHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculette.Addition value = null;

  public AdditionHolder ()
  {
  }

  public AdditionHolder (Calculette.Addition initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculette.AdditionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculette.AdditionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculette.AdditionHelper.type ();
  }

}
