package Calculette;


/**
* Calculette/DivisionPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculette.idl
* Wednesday, April 13, 2022 6:39:29 PM CEST
*/

public class DivisionPOATie extends DivisionPOA
{

  // Constructors

  public DivisionPOATie ( Calculette.DivisionOperations delegate ) {
      this._impl = delegate;
  }
  public DivisionPOATie ( Calculette.DivisionOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public Calculette.DivisionOperations _delegate() {
      return this._impl;
  }
  public void _delegate (Calculette.DivisionOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int div (int a, int b) throws Calculette.DivisionParZero
  {
    return _impl.div(a, b);
  } // div

  private Calculette.DivisionOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class DivisionPOATie
