package Calculette;


/**
* Calculette/MultiplicationPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculette.idl
* Wednesday, April 13, 2022 6:39:29 PM CEST
*/

public class MultiplicationPOATie extends MultiplicationPOA
{

  // Constructors

  public MultiplicationPOATie ( Calculette.MultiplicationOperations delegate ) {
      this._impl = delegate;
  }
  public MultiplicationPOATie ( Calculette.MultiplicationOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public Calculette.MultiplicationOperations _delegate() {
      return this._impl;
  }
  public void _delegate (Calculette.MultiplicationOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int mult (int a, int b)
  {
    return _impl.mult(a, b);
  } // mult

  private Calculette.MultiplicationOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class MultiplicationPOATie
