package Calculette;


/**
* Calculette/SoustractionPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculette.idl
* Wednesday, April 13, 2022 6:39:29 PM CEST
*/

public class SoustractionPOATie extends SoustractionPOA
{

  // Constructors

  public SoustractionPOATie ( Calculette.SoustractionOperations delegate ) {
      this._impl = delegate;
  }
  public SoustractionPOATie ( Calculette.SoustractionOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public Calculette.SoustractionOperations _delegate() {
      return this._impl;
  }
  public void _delegate (Calculette.SoustractionOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int sous (int a, int b)
  {
    return _impl.sous(a, b);
  } // sous

  private Calculette.SoustractionOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class SoustractionPOATie
