
package fr.lip6.org.calculatrice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatriceServiceService", targetNamespace = "http://org.lip6.fr/calculatrice", wsdlLocation = "file:/C:/Users/xskyl/Downloads/wildfly-10.0.0.Final/standalone/data/wsdl/TutoWebService.jar/CalculatriceServiceService.wsdl")
public class CalculatriceServiceService
    extends Service
{

    private final static URL CALCULATRICESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATRICESERVICESERVICE_EXCEPTION;
    private final static QName CALCULATRICESERVICESERVICE_QNAME = new QName("http://org.lip6.fr/calculatrice", "CalculatriceServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/xskyl/Downloads/wildfly-10.0.0.Final/standalone/data/wsdl/TutoWebService.jar/CalculatriceServiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATRICESERVICESERVICE_WSDL_LOCATION = url;
        CALCULATRICESERVICESERVICE_EXCEPTION = e;
    }

    public CalculatriceServiceService() {
        super(__getWsdlLocation(), CALCULATRICESERVICESERVICE_QNAME);
    }

    public CalculatriceServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATRICESERVICESERVICE_QNAME, features);
    }

    public CalculatriceServiceService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATRICESERVICESERVICE_QNAME);
    }

    public CalculatriceServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATRICESERVICESERVICE_QNAME, features);
    }

    public CalculatriceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatriceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Calculatrice
     */
    @WebEndpoint(name = "CalculatriceServicePort")
    public Calculatrice getCalculatriceServicePort() {
        return super.getPort(new QName("http://org.lip6.fr/calculatrice", "CalculatriceServicePort"), Calculatrice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculatrice
     */
    @WebEndpoint(name = "CalculatriceServicePort")
    public Calculatrice getCalculatriceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://org.lip6.fr/calculatrice", "CalculatriceServicePort"), Calculatrice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATRICESERVICESERVICE_EXCEPTION!= null) {
            throw CALCULATRICESERVICESERVICE_EXCEPTION;
        }
        return CALCULATRICESERVICESERVICE_WSDL_LOCATION;
    }

}
