
package fr.lip6.org.calculatrice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculatrice", targetNamespace = "http://org.lip6.fr/calculatrice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculatrice {


    /**
     * 
     * @param operande1
     * @param operande2
     * @return
     *     returns double
     */
    @WebMethod(action = "urn:additionner")
    @WebResult(name = "Resultat", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://org.lip6.fr/calculatrice", className = "fr.lip6.org.calculatrice.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://org.lip6.fr/calculatrice", className = "fr.lip6.org.calculatrice.AddResponse")
    public double add(
        @WebParam(name = "Operande1", targetNamespace = "")
        double operande1,
        @WebParam(name = "Operande2", targetNamespace = "")
        double operande2);

    /**
     * 
     * @param operande1
     * @param operande2
     * @return
     *     returns double
     */
    @WebMethod(action = "urn:multiplier")
    @WebResult(name = "Resultat", targetNamespace = "")
    @RequestWrapper(localName = "multiplier", targetNamespace = "http://org.lip6.fr/calculatrice", className = "fr.lip6.org.calculatrice.Multiplier")
    @ResponseWrapper(localName = "multiplierResponse", targetNamespace = "http://org.lip6.fr/calculatrice", className = "fr.lip6.org.calculatrice.MultiplierResponse")
    public double multiplier(
        @WebParam(name = "Operande1", targetNamespace = "")
        double operande1,
        @WebParam(name = "Operande2", targetNamespace = "")
        double operande2);

}
