package Calculette;


/**
* Calculette/DivisionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculette.idl
* Wednesday, April 13, 2022 6:39:29 PM CEST
*/

public abstract class DivisionPOA extends org.omg.PortableServer.Servant
 implements Calculette.DivisionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("div", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Calculette/Division/div
       {
         try {
           int a = in.read_long ();
           int b = in.read_long ();
           int $result = (int)0;
           $result = this.div (a, b);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (Calculette.DivisionParZero $ex) {
           out = $rh.createExceptionReply ();
           Calculette.DivisionParZeroHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Calculette/Division:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Division _this() 
  {
    return DivisionHelper.narrow(
    super._this_object());
  }

  public Division _this(org.omg.CORBA.ORB orb) 
  {
    return DivisionHelper.narrow(
    super._this_object(orb));
  }


} // class DivisionPOA
