package Calculette;

/**
* Calculette/DivisionParZeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculette.idl
* Wednesday, April 13, 2022 6:39:29 PM CEST
*/

public final class DivisionParZeroHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculette.DivisionParZero value = null;

  public DivisionParZeroHolder ()
  {
  }

  public DivisionParZeroHolder (Calculette.DivisionParZero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculette.DivisionParZeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculette.DivisionParZeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculette.DivisionParZeroHelper.type ();
  }

}
