package Calculette;

/**
* Calculette/MultiplicationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculette.idl
* Wednesday, April 13, 2022 6:39:29 PM CEST
*/

public final class MultiplicationHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculette.Multiplication value = null;

  public MultiplicationHolder ()
  {
  }

  public MultiplicationHolder (Calculette.Multiplication initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculette.MultiplicationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculette.MultiplicationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculette.MultiplicationHelper.type ();
  }

}
