package Calculette;

/**
* Calculette/SoustractionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculette.idl
* Wednesday, April 13, 2022 6:39:29 PM CEST
*/

public final class SoustractionHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculette.Soustraction value = null;

  public SoustractionHolder ()
  {
  }

  public SoustractionHolder (Calculette.Soustraction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculette.SoustractionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculette.SoustractionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculette.SoustractionHelper.type ();
  }

}
