package AdditionApp;


/**
* AdditionApp/AdditionPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* dimanche 17 avril 2022 12 h 05 CEST
*/

public class AdditionPOATie extends AdditionPOA
{

  // Constructors

  public AdditionPOATie ( AdditionApp.AdditionOperations delegate ) {
      this._impl = delegate;
  }
  public AdditionPOATie ( AdditionApp.AdditionOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public AdditionApp.AdditionOperations _delegate() {
      return this._impl;
  }
  public void _delegate (AdditionApp.AdditionOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int add (int a, int b)
  {
    return _impl.add(a, b);
  } // add

  public void shutdown ()
  {
    _impl.shutdown();
  } // shutdown

  private AdditionApp.AdditionOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class AdditionPOATie
